"""
AI Generate Service
-------------------
Accepts note text or extracted PDF text plus course_id and returns structured
flashcard + quiz drafts generated by OpenAI. If OpenAI can't be reached,
raises an error — no local parser fallback.

Environment:
  OPENAI_API_KEY         (required)
  AI_GENERATE_PROVIDER   (must be 'openai')
  OPENAI_MODEL           (optional, defaults to 'gpt-4o-mini')
"""
import json as _json
import os
from io import BytesIO


# ── dedupe + count helpers ───────────────────────────────────────────────

def _dedupe_flashcards(items: list[dict]) -> list[dict]:
    seen = set()
    deduped = []

    for item in items:
        front = (item.get("front") or "").strip()
        back = (item.get("back") or "").strip()
        key = (front.lower(), back.lower())

        if not front or not back:
            continue
        if key in seen:
            continue

        seen.add(key)
        deduped.append({"front": front, "back": back})

    return deduped


def _dedupe_questions(questions: list[dict]) -> list[dict]:
    seen = set()
    deduped = []

    for q in questions:
        question_text = (q.get("question_text") or "").strip()
        question_type = (q.get("question_type") or "").strip()
        answers = q.get("answers") or []

        if not question_text or not question_type:
            continue
        if len(answers) < 2:
            continue

        correct_count = sum(1 for a in answers if a.get("is_correct") is True)
        if correct_count != 1:
            continue

        key = question_text.lower()
        if key in seen:
            continue

        cleaned_answers = []
        answer_seen = set()

        for a in answers:
            answer_text = (a.get("answer_text") or "").strip()
            is_correct = bool(a.get("is_correct"))

            if not answer_text:
                continue
            if answer_text.lower() in answer_seen:
                continue

            answer_seen.add(answer_text.lower())
            cleaned_answers.append({
                "answer_text": answer_text,
                "is_correct": is_correct
            })

        if len(cleaned_answers) < 2:
            continue

        correct_count = sum(1 for a in cleaned_answers if a["is_correct"] is True)
        if correct_count != 1:
            continue

        seen.add(key)
        deduped.append({
            "question_text": question_text,
            "question_type": question_type,
            "points": q.get("points", 1),
            "answers": cleaned_answers
        })

    return deduped


def _target_counts(raw_text: str) -> tuple[int, int]:
    """
    Scale desired number of flashcards and quiz questions by content length.
    Short notes get the minimum (10); long notes scale up to 25.
    """
    words = len((raw_text or "").split())
    target = max(10, min(25, 10 + words // 200))
    return target, target


# ── OpenAI-backed generator ──────────────────────────────────────────────

class AIGenerateError(Exception):
    """Raised when the OpenAI generation pipeline can't complete."""


def extract_text_from_pdf_bytes(pdf_bytes: bytes) -> str:
    """Extract and normalize text from a PDF upload."""
    try:
        from pypdf import PdfReader
    except ImportError as e:
        raise ValueError("PDF support requires the 'pypdf' package") from e

    if not pdf_bytes:
        raise ValueError("The uploaded PDF is empty")

    try:
        reader = PdfReader(BytesIO(pdf_bytes))
    except Exception as e:
        raise ValueError(f"Could not read PDF: {type(e).__name__}: {e}") from e

    parts: list[str] = []
    for page in reader.pages:
        text = (page.extract_text() or "").strip()
        if text:
            parts.append(text)

    extracted = "\n\n".join(parts).strip()
    if not extracted:
        raise ValueError("The uploaded PDF did not contain extractable text")

    return extracted


def _call_openai(course_id: int | None, raw_text: str, kind: str = "both") -> dict:
    """
    Call OpenAI to generate flashcards and/or quiz questions.
    `kind` can be:
      - "quiz"       → only quiz questions
      - "flashcards" → only flashcards
      - "both"       → both (default)
    Raises AIGenerateError on any failure.
    """
    try:
        import openai as _openai
    except ImportError as e:
        raise AIGenerateError(
            "openai Python package is not installed on the server"
        ) from e

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise AIGenerateError("OPENAI_API_KEY is not set in the server environment")

    n_cards, n_questions = _target_counts(raw_text)
    want_cards = kind in ("flashcards", "both")
    want_quiz  = kind in ("quiz",       "both")

    # ---- Build a prompt that asks ONLY for the requested type(s) ----
    sections: list[str] = []
    rules: list[str] = []
    if want_cards:
        sections.append(
            '  "flashcard_set": {\n'
            '    "title": "<short title based on the notes>",\n'
            '    "description": "<one sentence description>",\n'
            '    "items": [{"front": "<question or prompt>", "back": "<answer or explanation>"}]\n'
            "  }"
        )
        rules.append(f"- items array must have exactly {n_cards} objects")
    if want_quiz:
        sections.append(
            '  "quiz": {\n'
            '    "title": "<short quiz title>",\n'
            '    "description": "<one sentence description>",\n'
            '    "questions": [{\n'
            '      "question_text": "<question>",\n'
            '      "question_type": "multiple_choice",\n'
            '      "points": 1,\n'
            '      "answers": [\n'
            '        {"answer_text": "<correct option>", "is_correct": true},\n'
            '        {"answer_text": "<wrong option>", "is_correct": false},\n'
            '        {"answer_text": "<wrong option>", "is_correct": false},\n'
            '        {"answer_text": "<wrong option>", "is_correct": false}\n'
            "      ]\n"
            "    }]\n"
            "  }"
        )
        rules.append(f"- questions array must have exactly {n_questions} objects")
        rules.append("- every question must have exactly 4 answers, exactly 1 with is_correct=true")
        rules.append("- questions must be real MCQ style, not fill-in-the-blank")

    ask = (
        f"Given student notes, produce "
        + (f"exactly {n_cards} flashcards" if want_cards else "")
        + (" and " if want_cards and want_quiz else "")
        + (f"exactly {n_questions} multiple-choice quiz questions" if want_quiz else "")
        + "."
    )

    system_prompt = (
        "You are a study-material generator. "
        + ask + " "
        + "Return ONLY a JSON object with this exact schema:\n\n"
        + "{\n" + ",\n".join(sections) + "\n}\n\n"
        + "Rules:\n"
        + "\n".join(rules) + "\n"
        + "- base all content strictly on the provided notes, do not invent facts\n"
        + "- no markdown, no LaTeX, no code blocks inside strings"
    )

    try:
        client = _openai.OpenAI(api_key=api_key, timeout=45.0)
        response = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
            response_format={"type": "json_object"},
            max_tokens=6000,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": raw_text},
            ],
        )
        data = _json.loads(response.choices[0].message.content)
        print(
            f"[ai_generate] OpenAI OK — target {n_cards} cards / {n_questions} questions"
        )
    except Exception as e:
        print(f"[ai_generate] OpenAI call FAILED: {type(e).__name__}: {e}")
        raise AIGenerateError(f"OpenAI call failed: {type(e).__name__}: {e}") from e

    # ---- Parse + validate the JSON response ----
    try:
        fc_block = data.get("flashcard_set") or data.get("flashcards") or {}
        qz_block = data.get("quiz") or data.get("quiz_set") or {}

        flashcard_items: list[dict] = []
        if want_cards:
            for item in (fc_block.get("items") or fc_block.get("cards") or []):
                front = str(item.get("front") or item.get("question") or "").strip()
                back = str(item.get("back") or item.get("answer") or "").strip()
                if front and back:
                    flashcard_items.append({"front": front, "back": back})

        quiz_questions: list[dict] = []
        if want_quiz:
            for q in (qz_block.get("questions") or []):
                qtext = str(q.get("question_text") or q.get("question") or "").strip()
                answers = []
                for a in (q.get("answers") or q.get("options") or []):
                    atext = str(a.get("answer_text") or a.get("text") or "").strip()
                    raw_c = a.get("is_correct") or a.get("correct")
                    is_correct = raw_c is True or str(raw_c).lower() == "true"
                    if atext:
                        answers.append({"answer_text": atext, "is_correct": is_correct})
                if qtext and answers:
                    quiz_questions.append({
                        "question_text": qtext,
                        "question_type": str(q.get("question_type") or "multiple_choice"),
                        "points": int(q.get("points") or 1),
                        "answers": answers,
                    })

        flashcard_items = _dedupe_flashcards(flashcard_items)[:n_cards]
        quiz_questions = _dedupe_questions(quiz_questions)[:n_questions]

        if want_cards and not flashcard_items:
            raise AIGenerateError("OpenAI returned no usable flashcards")
        if want_quiz and not quiz_questions:
            raise AIGenerateError("OpenAI returned no usable quiz questions")

        return {
            "status": "ok",
            "source": "openai",
            "course_id": course_id,
            "draft": {
                "flashcard_set": {
                    "title":       str(fc_block.get("title") or "Generated from Notes"),
                    "description": str(fc_block.get("description") or "AI-generated flashcards."),
                    "items":       flashcard_items,
                },
                "quiz": {
                    "title":       str(qz_block.get("title") or "Generated Quiz"),
                    "description": str(qz_block.get("description") or "AI-generated quiz."),
                    "questions":   quiz_questions,
                },
            },
            "meta": {
                "flashcard_count": len(flashcard_items),
                "question_count":  len(quiz_questions),
                "truncated":       False,
            },
        }
    except AIGenerateError:
        raise
    except Exception as e:
        print(f"[ai_generate] OpenAI response parse FAILED: {type(e).__name__}: {e}")
        raise AIGenerateError(
            f"OpenAI response couldn't be parsed: {type(e).__name__}: {e}"
        ) from e


def generate_study_drafts(
    course_id: int | None,
    raw_text: str,
    user_id: int | None = None,  # accepted for caller compatibility
    kind: str = "both",
) -> dict:
    cleaned_text = (raw_text or "").strip()
    if not cleaned_text:
        raise ValueError("raw_text is required")

    if kind not in ("quiz", "flashcards", "both"):
        raise ValueError("kind must be one of: quiz, flashcards, both")

    # gpt-4o-mini handles this comfortably in context.
    max_input_chars = 18000
    truncated = len(cleaned_text) > max_input_chars
    cleaned_text = cleaned_text[:max_input_chars]

    if os.getenv("AI_GENERATE_PROVIDER") != "openai":
        raise AIGenerateError(
            "AI_GENERATE_PROVIDER must be set to 'openai' on the server"
        )

    _ = user_id  # reserved for future per-user logic
    result = _call_openai(course_id=course_id, raw_text=cleaned_text, kind=kind)
    result["meta"]["truncated"] = truncated
    result["kind"] = kind
    return result
