// By Rise Akizaki

import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { registerUser, loginUser} from "../api/auth.js"; // all methods from the api go here
import { API_BASE } from "../api/base.js";
import LoginSuccessOverlay from "../components/LoginSuccessOverlay.js";

// Fetch the logged-in user's first_name from /user/account (session cookie is set by login)
async function fetchFirstName(): Promise<string | undefined> {
  try {
    const res = await fetch(`${API_BASE}/user/account`, { credentials: "include" });
    if (!res.ok) return undefined;
    const data = await res.json();
    const u = data?.user || data;
    return u?.first_name || undefined;
  } catch {
    return undefined;
  }
}

// For the user registration page
// Most of the initial code was generated by ChatGPT as a starting point
export function RegisterPage() {
  const [form, setForm] = useState({
    first_name: "",
    last_name: "",
    email: "",
    password: "",
    college_id: "",
    major_id: "",
    bio: ""
  });

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [showSuccess, setShowSuccess] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  }; // Generated with ChatGPT

  const handleRegister = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();

    setLoading(true);
    setError("");
    setMessage("");

    try {
      const data = await registerUser(form);
      setMessage(data.message);
      // Immediately log the user in with the same credentials so the
      // session cookie is set before we navigate to /home.
      try {
        await loginUser({ email: form.email, password: form.password });
      } catch {
        // If auto-login fails for any reason, fall back to redirecting to /login.
        setShowSuccess(true);
        return;
      }
      // Trigger the rising-tide animation — onComplete will navigate to /home.
      setShowSuccess(true);
    }
    catch (error) {
      if (error instanceof Error) {
        setError(error.message);
      }
      else {
        setError("Registration failed");
      }
      setLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <LoginSuccessOverlay
        show={showSuccess}
        captainName={form.first_name || undefined}
        onComplete={() => {
          // Auto-logged in during handleRegister, go straight to home
          window.location.href = "/home";
        }}
      />
      <div className = "auth-card">
        <h1 className="auth-title">Register</h1>

        <form onSubmit={handleRegister} className = "auth-form">
          <input
            name="first_name"
            placeholder="First Name"
            value={form.first_name}
            onChange={handleChange}
            className="auth-input"
          />

          <input
            name="last_name"
            placeholder="Last Name"
            value={form.last_name}
            onChange={handleChange}
            className="auth-input"
          />

          <input
            name="email"
            placeholder="Email"
            value={form.email}
            onChange={handleChange}
            className="auth-input"
          />

          <input
            type="password"
            name="password"
            placeholder="Password"
            value={form.password}
            onChange={handleChange}
            className="auth-input"
          />

          <button type="submit" disabled={loading}             
          className= "auth-button"
          >
            {loading ? "Registering..." : "Register"}
          </button>
        </form>

        {message && <p style={{ color: "lightgreen" }}>{message}</p>}
        {error && <p style={{ color: "#ff6b6b" }}>{error}</p>}
      </div>
    </div>
  );
}

// for the user login page
export function LoginPage() {
  const [form, setForm] = useState({
    email: "",
    password: "",
  });

  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [captainName, setCaptainName] = useState<string | undefined>(undefined);
  const navigate = useNavigate();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({...form, [e.target.name]: e.target.value});
  };

  const handleLogin = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    setMessage("");

    try {
      const data = await loginUser(form);
      setMessage(data.message);
      // Grab the captain's first name — try response first, then fetch account.
      const name =
        data?.user?.first_name ||
        data?.first_name ||
        data?.user?.name ||
        (await fetchFirstName());
      setCaptainName(name);
      // Trigger the rising-tide animation. LoginSuccessOverlay will
      // call onComplete when it finishes, which navigates to /home.
      setShowSuccess(true);
    }
    catch (error) {
      if (error instanceof Error) {
        setError(error.message);
      }
      else {
        setError("Login failed");
      }
      setLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <LoginSuccessOverlay
        show={showSuccess}
        captainName={captainName}
        onComplete={() => navigate("/home", { replace: true })}
      />
      <div className="auth-card">
        <h1 className="auth-title">Login</h1>

        <form onSubmit={handleLogin} className = "auth-form">
          <input
            name="email"
            placeholder="Email"
            value={form.email}
            onChange={handleChange}
            className="auth-input"
          />

          <input
            type="password"
            name="password"
            placeholder="Password"
            value={form.password}
            onChange={handleChange}
            className="auth-input"
          />

          <button 
            type="submit" 
            disabled={loading} 
            className="auth-button">
            {loading ? "Logging in..." : "Login"}
          </button>

          <button
            type="button"
            onClick={() => (window.location.href = "/register")}
            className="auth-button"
          >
            Register
          </button>
        </form>

        {message && <p style={{ color: "lightgreen" }}>{message}</p>}
        {error && <p style={{ color: "#ff6b6b" }}>{error}</p>}
      </div>
    </div>
  );
}

// default style for web page
// Initial style generated by ChatGPT
////////////////////////////
// const styles: { [key: string]: React.CSSProperties } = {
//   page: {
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//     minHeight: "100vh",
//     padding: "20px",
//   },
//   card: {
//     background: "#242452",
//     backdropFilter: "blur(10px)",
//     padding: "30px",
//     width: "100%",
//     maxWidth: "420px",
//     border: "1px solid rgb(120, 120, 120)",
//     borderRadius: "12px",
//   },
//   title: {
//     textAlign: "center",
//     color: "white",
//     marginBottom: "20px",
//   },
//   form: {
//     display: "flex",
//     flexDirection: "column",
//     gap: 12, // use number instead of string "12px"
//   },
//   input: {
//     padding: "12px 14px",
//     borderRadius: 6, // number works here too
//     border: "1px solid rgba(255,255,255,0.1)",
//     fontSize: 16,
//     backgroundColor: "rgba(10, 15, 26, 0.8)",
//     color: "white",
//     outline: "none",
//   },
//   button: {
//     marginTop: 10,
//     padding: "10px 14px",
//     background: "#0ea5e9",
//     color: "white",
//     fontSize: 16,
//     borderRadius: 6,
//     border: "none",
//     cursor: "pointer",
//     transition: "0.2s",
//   },
// };
